### Adding, removing, and sorting elements

In [3]:
import numpy as np

In [21]:
x = np.array([1, 35, 5, 4])
y = np.array([12, 34, 33, 98])

In [22]:
# It didn't add 100 to the end of the array, it created a new array with 100 at the end. The original array x remains unchanged.
x = np.append(x, 100)
x

array([  1,  35,   5,   4, 100])

In [23]:
# It didn't delete the first element of the array, it created a new array without the first element. The original array x remains unchanged.
np.delete(x, 0)  # Delete the first element of the array

array([ 35,   5,   4, 100])

In [24]:
# Update the value at index 4 to 50
x[4] = 50
x

array([ 1, 35,  5,  4, 50])

In [27]:
np.sort(y)  # Sort the array y in ascending order
y

array([12, 33, 34, 98])

#### Operations with a Scalar
Operation on the entire array.

In [4]:
arr = np.array([2, 3, 5, 9])

print("Addition:", arr + 5)
print("Subtraction:", arr - 2)
print("Multiplication:", arr * 10)
print("Division:", arr / 4)
print("Floor Division:", arr // 3)
print("Modulus:", arr % 2)
print("Power:", arr ** 2)

Addition: [ 7  8 10 14]
Subtraction: [0 1 3 7]
Multiplication: [20 30 50 90]
Division: [0.5  0.75 1.25 2.25]
Floor Division: [0 1 1 3]
Modulus: [0 1 1 1]
Power: [ 4  9 25 81]


#### Concatenating Arrays

In [91]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.concatenate([a, b])

array([1, 2, 3, 4, 5, 6])

#### Arithmetic Operations

In [19]:
print("Addition:", x+y)
print("Subtraction:", y-x)
print("Multiplication:", x*y)
print("Division:", y/x)
print("Floor Division:", y//x)
print("Modulus:", x % 2)
print("Power:", x ** 2)

Addition: [ 4  7  7 10]
Subtraction: [ 0  1 -3 -8]
Multiplication: [ 4 12 10  9]
Division: [1.         1.33333333 0.4        0.11111111]
Floor Division: [1 1 0 0]
Modulus: [0 1 1 1]
Power: [ 4  9 25 81]


In [ ]:
x = np.array([2, 3, 5, 9])
y = np.array([2, 4, 2, 1])
z = np.array([2, 3, -4, -9])

print("Addition:", np.add(x, y))
print("Subtraction:", np.subtract(x, y))
print("Multiplication:", np.multiply(x, y))
print("Division:", np.divide(x, y))
print("Modulus:", np.mod(x, y))
print("Reminder:", np.remainder(x, y))
print("Power:", np.power(x, y))
print("Quotient and Mod:", np.divmod(x, y))
print("Absolute:", np.absolute(z))
print("Absolute:", np.abs(z))

#### Mathematical Functions

In [31]:
arr = np.array(np.arange(1, 11))


In [32]:
print("Cummulative Sum:", np.cumsum(arr))

Cummulative Sum: [ 1  3  6 10 15 21 28 36 45 55]


In [33]:
print("Cummulative product:", np.cumprod(arr))

Cummulative product: [      1       2       6      24     120     720    5040   40320  362880
 3628800]


In [37]:
arr = np.array([10, 15, 25, 5])

"""Differences
A discrete difference means subtracting two successive elements.

E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]"""
print("Difference:", np.diff(arr))


"""We can perform this operation repeatedly by giving parameter n.

E.g. for [1, 2, 3, 4], the discrete difference with n = 2 would be [2-1, 3-2, 4-3] = [1, 1, 1] , 
then, since n=2, we will do it once more, with the new result: [1-1, 1-1] = [0, 0]"""
print("Difference:", np.diff(arr, n=2))
# Returns: [5 -30] because: 15-10=5, 25-15=10, and 5-25=-20 AND 10-5=5 and -20-10=-30



Difference: [  5  10 -20]
Difference: [  5 -30]


In [36]:
print("Square Root:", np.sqrt(arr))

Square Root: [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]


In [37]:
print("Exponential:", np.exp(arr))

Exponential: [1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04]


In [38]:
print("Log:", np.log(arr))

Log: [      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458 2.30258509]


/tmp/ipykernel_172629/1341110773.py:1: RuntimeWarning: divide by zero encountered in log
  print("Log:", np.log(arr))


In [39]:
arr = np.array([1, 2, -4, -10, 19])
print("Absolute Value:", np.abs(arr))

Absolute Value: [ 1  2  4 10 19]


Trigonometry

In [43]:
print("Sin:", np.sin(arr))
print("Cos:", np.cos(arr))
print("Tan:", np.tan(arr))

Sin: [0.84147098 0.90929743 0.7568025  0.54402111 0.14987721]
Cos: [ 0.54030231 -0.41614684 -0.65364362 -0.83907153  0.98870462]
Tan: [ 1.55740772 -2.18503986 -1.15782128 -0.64836083  0.15158947]


#### Rounding Decimals

In [14]:
arr = np.array([-3.16666, 3.666667])

print("Truncate:", np.trunc(arr))


Truncate: [-3.  3.]


In [16]:
# The around() function increments preceding digit or decimal by 1 if >=5 else do nothing.
arr = np.array([1.333334, 3.456, 5.223, 4.56])
print("Around:", np.around(arr))


Around: [1. 3. 5. 5.]


In [17]:
arr = np.array([-3.1666, 3.6667])
print("Floor:", np.floor(arr))

Floor: [-4.  3.]


In [18]:
arr = np.array([-3.1666, 3.6667])
print("Ceil:", np.ceil(arr))

Ceil: [-3.  4.]


#### Aggregate Operations

In [44]:
arr = np.array(np.arange(10, 100, 10))
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [23]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

print("Sum:" ,np.sum(arr))
print("Product:" ,np.prod(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))

Sum: 450
Product: 362880000000000
Minimum: 10
Maximum: 90


#### Statistical Operations

In [56]:
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:" ,np.std(arr))
print("Variance", np.var(arr))

Mean: 50.0
Median: 50.0
Standard Deviation: 25.81988897471611
Variance 666.6666666666666


#### Axis Operation

In [25]:
arr = np.array(np.arange(1, 7)).reshape(2, 3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
print("Sum of Everything:", np.sum(arr))

print("Sum of columns:", np.sum(arr, axis = 0))

print("Sum of rows:", np.sum(arr, axis = 1))

Sum of Everything: 21
Sum of columns: [5 7 9]
Sum of rows: [ 6 15]


The same concept works with:

In [26]:
np.mean(arr, axis=0)
np.mean(arr, axis=1)

np.max(arr, axis=0)
np.max(arr, axis=1)

np.min(arr, axis=0)
np.min(arr, axis=1)

np.prod(arr, axis=0)
np.prod(arr, axis=1)


array([  6, 120])

#### Comparision Operations

In [62]:
arr = np.array([10, 20, 30, 40])

In [63]:
arr > 20

array([False, False,  True,  True])

In [64]:
arr == 20

array([False,  True, False, False])

In [65]:
arr <= 20

array([ True,  True, False, False])

#### Boolean Indexing

In [67]:
arr = np.array(np.arange(10, 100, 5))
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [71]:
arr[ arr >= 50 ]

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [69]:
arr[ arr == 50 ]

array([50])

In [70]:
arr[ arr != 50 ]

array([10, 15, 20, 25, 30, 35, 40, 45, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [73]:
arr[ arr % 2 == 0 ]

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

#### Where
- Returns the indices where the condition is true.

In [74]:
arr = np.array(np.arange(10, 100, 5))
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [75]:
np.where( arr > 50)

(array([ 9, 10, 11, 12, 13, 14, 15, 16, 17]),)

You can also replace values conditionally:

In [82]:
np.where( arr < 50, arr, arr ** 2)

array([  10,   15,   20,   25,   30,   35,   40,   45, 2500, 3025, 3600,
       4225, 4900, 5625, 6400, 7225, 8100, 9025])

In [81]:
np.where( arr % 2 == 0, "Even", "Odd")

array(['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd'],
      dtype='<U4')

#### Finding Minimum/Maximum Index

In [86]:
arr = np.array([2, 5, 7, 12, 33, 45, 89, 0, 43, 21, 8])

In [89]:

print("Maximum Index:", np.argmax(arr))
print("Minimum Index:", np.argmin(arr))

Maximum Index: 6
Minimum Index: 7
