### Broadcasting
- One of the most import NumPy Concepts

In [1]:
import numpy as np

1. Scalar to Array (The Simplest Broadcasting)



In [2]:
import numpy as np

matrix = np.array([1, 2, 3])
result = matrix + 10  # 10 is broadcasted to [10, 10, 10]

print(result)
# Output: [11 12 13]


[11 12 13]



2. 1D Array to 2D Array



In [3]:
import numpy as np

# A 2x3 matrix
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])

# A 1D array of shape (3,)
row_vector = np.array([10, 20, 30])

# The row_vector is broadcasted vertically to match the (2,3) shape
result = matrix + row_vector

print(result)
# Output:
# [[11 22 33]
#  [14 25 36]]


[[11 22 33]
 [14 25 36]]



#### 📏 The 3 Rules of Broadcasting

To determine if two arrays are compatible for broadcasting, NumPy evaluates their shapes from right to left (starting with the trailing dimensions) using three main rules

| **Rule** | **Explanation** | **Example** |
|---|---|---|
| **1. Dimension Padding** | If the arrays have a different number of dimensions, the shape of the smaller one is **padded with ones on the left side**. | Comparing `(3, 4)` and `(4,)`<br>↳ The second becomes `(1, 4)` |
| **2. Size-1 Stretching** | If an array has a **size of 1** in a specific dimension, it is stretched to match the larger array's size in that dimension. | Array A: `(3, 4)`<br>Array B: `(1, 4)`<br>↳ Stretches to `(3, 4)` |
| **3. Failure / Error** | If the sizes do not match in any dimension and **neither is equal to 1**, broadcasting fails and throws a `ValueError`. | Comparing `(3, 4)` and `(3, 2)`<br>↳ **Fails** (`4` vs `2` mismatch) |


#### Compatible vs. Incompatible Shapes Matrix

| **Array A Shape** | **Array B Shape** | **Broadcastable?** | **Resulting Shape** |
|---|---|---|---|
| `(4, 3)` | `(4, 3)` | **Yes** (Exact match) | `(4, 3)` |
| `(4, 3)` | `(3,)` | **Yes** (Becomes `(1, 3)` → stretches to `(4, 3)`) | `(4, 3)` |
| `(4, 1)` | `(1, 3)` | **Yes** (Both stretch along their respective `1` axes) | `(4, 3)` |
| `(4, 3)` | `(4,)` | **No** (Trailing dimensions `3` and `4` do not match) | — |

### Vectorization

- It is the practice of performing mathematical operations on entire arrays at once instead of using explicit Python loops (like for or while).

In [4]:
# ❌ The Slow Way: Python for Loop
import numpy as np

arr = np.arange(1_000_000)

# Iterating line-by-line in pure Python
result = [x * 2 for x in arr] 


# The Fast Way: NumPy Vectorization
import numpy as np

arr = np.arange(1_000_000)

# Done instantly in optimized C code
result = arr * 2 



Vectorization
→ "Can I perform this operation on the whole array without a Python loop?"

Broadcasting
→ "Can NumPy make these different-shaped operands compatible?"