# NumPy Linear Algebra

Linear algebra is the study of calculations with vectors and matrices. This notebook introduces NumPy tools for creating matrices, multiplying them, solving linear systems, and performing matrix decompositions.

A matrix is commonly written as $A \in \mathbb{R}^{m \times n}$, where $m$ is the number of rows and $n$ is the number of columns.

## Vectors and Shapes

A vector is a one-dimensional sequence of numbers. Its `shape` tells how many elements it contains; for example, shape $(n,)$ means a vector with $n$ values.

In [2]:
import numpy as np

In [11]:
x = np.array([2, 3, 4, 5])
y = np.array([10, 20, 30, 40])

print(x)
print(y)
print(x.shape)
print(y.shape)

[2 3 4 5]
[10 20 30 40]
(4,)
(4,)


### Dot Product

The dot product multiplies corresponding vector elements and adds the products. For vectors $x,y \in \mathbb{R}^n$:

$$x \cdot y = \sum_{i=1}^{n} x_i y_i$$

For example, `np.dot(x, y)` is equivalent to `np.sum(x * y)` for 1D vectors.

In [13]:
np.dot(2, 4)

np.int64(8)

In [15]:
np.dot(
    [2, 2], 
    [4, 3]
)

np.int64(14)

In [12]:
np.dot(x, y)

# Is Equavalent to
np.sum(x * y)

np.int64(400)

### Matrix Multiplication

For matrices $A \in \mathbb{R}^{m \times n}$ and $B \in \mathbb{R}^{n \times p}$, the product $C = AB$ is defined only when the inner dimensions match. The result has shape $(m, p)$, with entries:

$$C_{ij} = \sum_{k=1}^{n} A_{ik}B_{kj}$$

In [25]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

[[ 2  3  4  5]
 [ 6  8 20  4]]
[[3 3]
 [2 2]
 [4 1]
 [2 3]]


array([[ 38,  31],
       [122,  66]])

### The `@` Operator and Transpose

For 2D arrays, `@` performs matrix multiplication (the same operation as `np.matmul`). A transpose swaps rows and columns: if $Y$ has shape $(m,n)$, then $Y^T$ has shape $(n,m)$. This can make the inner dimensions align for a product.

$$(Y^T)_{ij} = Y_{ji}$$

In [56]:
x = np.array([ [2, 3, 4, 5], [6, 8, 20, 4]])
y = np.array([ [3, 2, 4, 2], [3, 2, 1, 3 ]])


print("X shape:", x.shape)
print("Y shape:", y.shape)
print("Y Transpose shape:", y.T.shape)

print(x)
print(y)
print(y.T)

x @ y.T

X shape: (2, 4)
Y shape: (2, 4)
Y Transpose shape: (4, 2)
[[ 2  3  4  5]
 [ 6  8 20  4]]
[[3 2 4 2]
 [3 2 1 3]]
[[3 3]
 [2 2]
 [4 1]
 [2 3]]


array([[ 38,  31],
       [122,  66]])

### Creating Arrays and Special Matrices

- `np.eye(n)` creates an $n \times n$ identity matrix; `np.identity(n)` is another way to create a square identity matrix. The identity matrix has $I_{ij}=1$ when $i=j$, and $0$ otherwise.
- `np.zeros(shape)` and `np.ones(shape)` fill an array with zeros or ones.
- `np.full(shape, c)` fills an array with a chosen constant $c$.
- `np.empty(shape)` allocates an array without initializing its entries; its initial values are unspecified and should be overwritten before use.

In [57]:
np.eye(5, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [58]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [59]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [60]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [61]:
np.full((3, 3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [62]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [63]:
arr = np.empty(5)


In [64]:
arr

array([0., 0., 0., 0., 0.])

### Matrix Conversion and Evenly Spaced Values

`np.asmatrix(x)` converts input into NumPy's matrix type; in most modern NumPy code, regular `ndarray` objects are preferred. `np.linspace(start, stop, num)` returns `num` evenly spaced values from `start` to `stop`, including both endpoints by default.

In [65]:
x = np.array([[1, 2], [3, 4]])
np.asmatrix(x)

matrix([[1, 2],
        [3, 4]])

In [66]:
np.linspace(1, 11, num=10)

array([ 1.        ,  2.11111111,  3.22222222,  4.33333333,  5.44444444,
        6.55555556,  7.66666667,  8.77777778,  9.88888889, 11.        ])

### Solving a Linear System

A linear system can be written as $Ax=b$, where $A$ contains the coefficients, $x$ is the unknown vector, and $b$ contains the results. `np.linalg.solve(A, b)` finds $x$ directly.

$$x = A^{-1}b$$

In practice, `solve` is preferred to explicitly computing $A^{-1}$.

In [ ]:
A = np.array([
    [2, 1],
    [1, 1]
])

b = np.array([8, 5])

solution = np.linalg.solve(A, b)

print(solution)

[3. 2.]


### Determinant

The determinant is a single number associated with a square matrix. It indicates whether the matrix is invertible: if $\det(A) \ne 0$, then $A$ is invertible; if $\det(A)=0$, it is singular.

For a $2 \times 2$ matrix:

$$A = \begin{bmatrix} a & b \\ c & d \end{bmatrix}, \qquad \det(A)=ad-bc$$

In [70]:
A = np.array([
    [10, 5],
    [4, 3]
])

print(np.linalg.det(A))

10.000000000000002


### Matrix Inverse

For an invertible square matrix $A$, its inverse $A^{-1}$ satisfies:

$$AA^{-1}=A^{-1}A=I$$

The inverse exists only when $\det(A) \ne 0$. In NumPy, `np.linalg.inv(A)` computes it.

In [73]:
A = np.array([
    [2, 1],
    [1, 1]
])

A_inv = np.linalg.inv(A)

print(A_inv)

# AA -1 = I
print(A @ A_inv)

[[ 1. -1.]
 [-1.  2.]]
[[1. 0.]
 [0. 1.]]


### Matrix Rank

The rank is the number of linearly independent rows or columns in a matrix. It describes how much independent information the matrix contains. A $2 \times 2$ matrix with rank $1$ has dependent rows or columns and determinant $0.

In [74]:
A = np.array([
    [1, 2],
    [2, 4]
])

print(np.linalg.det(A))  # Approximately 0
print(np.linalg.matrix_rank(A))  # 1

0.0
1


### Eigenvalues, Eigenvectors, and Vector Norm

For a square matrix $A$, an eigenvector $v$ is a nonzero vector whose direction is unchanged by $A$. Its eigenvalue $\lambda$ is the scale factor:

$$Av=\lambda v$$

The Euclidean norm (length) of a vector is:

$$\|v\|_2 = \sqrt{\sum_{i=1}^{n} v_i^2}$$

`np.linalg.eig(A)` returns eigenvalues and eigenvectors; `np.linalg.norm(v)` computes the Euclidean norm by default.

In [82]:
A = np.array([
    [2, 0],
    [0, 3]
])

eigenvalues, eigenvectors = np.linalg.eig(A)

print(eigenvalues)
print(eigenvectors)


A = np.array([2, 3])
B = np.array([5, 7])

distance = np.linalg.norm(A - B)

print(distance)  # 5.0

[2.+0.j 3.+0.j]
[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]
5.0


In [80]:
v = np.array([3, 4])
print(np.linalg.norm(v))

5.0


### Euclidean Distance

The Euclidean distance between two vectors is the norm of their difference. For vectors $a$ and $b$:

$$d(a,b)=\|a-b\|_2 = \sqrt{\sum_{i=1}^{n}(a_i-b_i)^2}$$

The example computes this with `np.linalg.norm(A - B)`.

In [78]:
A = np.array([2, 3])
B = np.array([5, 7])

distance = np.linalg.norm(A - B)

print(distance)  # 5.0

5.0


### Singular Value Decomposition (SVD)

SVD factors a matrix $A$ into two orthogonal matrices and a diagonal matrix of nonnegative singular values:

$$A = U\Sigma V^T$$

The singular values describe the strength of independent directions in the data. `np.linalg.svd(A)` returns $U$, the singular values $S$, and $V^T$ (named `Vt` in the code).

In [83]:
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

U, S, Vt = np.linalg.svd(A, full_matrices=False)

print("U shape:", U.shape)
print("Singular values:", S)
print("Vt shape:", Vt.shape)

U shape: (3, 2)
Singular values: [9.52551809 0.51430058]
Vt shape: (2, 2)


### Reconstructing the Matrix

For the reduced SVD used above, `np.diag(S)` creates the diagonal matrix $\Sigma$ from the singular values. Multiplying the factors recovers the original matrix (up to floating-point rounding):

$$A_{\text{reconstructed}} = U\Sigma V^T \approx A$$

`np.allclose` checks whether the two arrays are numerically close within a tolerance.

In [84]:
Sigma = np.diag(S)

A_reconstructed = U @ Sigma @ Vt

print(np.allclose(A, A_reconstructed))
# True

True
