### Indexing
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [1]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5])

print(arr[0])
print(arr[1])
print(arr[2])


1
2
3


Access 2-D Arrays

In [6]:
arr_2d = np.array(
    [
        [1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10]
    ]
)

"""
Exercise:

Access 9 from second row.

"""

# One way
print(arr_2d[1][3])

# Another way
print(arr_2d[1, 3])


9
9


Access 3-D Arrays

In [21]:
arr_3d = np.array(
    
    [
        [
            [1, 2, 3, 4, 5],
            [6, 7, 8, 9, 10]
        ],
        [
            [11, 22, 33, 44, 55],
            [66, 77, 88, 99, 110]

        ],
        [
            [111, 222, 333, 444, 555],
            [666, 777, 888, 999, 1110]
        ]
    ],
)

"""
Exercise:

Access 44 element.

"""
# One way
print(arr_3d[1][0][3])

# Another way
print(arr_3d[1, 0, 3])


44
44


Negative Indexing

In [27]:
arr = np.array([1, 2, 3, 4, 5])

print(arr[-1])

5


In [29]:
arr = np.array(
    [
        [1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10]
    ]
)

print(arr[-1][-3])
print(arr[-1, -3])

8
8


### Slicing

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

Note: The result includes the start index, but excludes the end index.


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4])

[2 3 4]


In [33]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[:4])

[1 2 3 4]


In [34]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[3:])

[4 5]


Negative Indexing

In [36]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[-4:-1])

[2 3 4]


Step

In [41]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


2-D Array

In [ ]:
arr = np.array(
    [
        [1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10]
    ]
)

print(arr[1][1:4])
print(arr[1, 1:4])

[7 8 9]
7


In [51]:
arr = np.array(
    [
        [1, 2, 3, 4, 5], 
        [6, 7, 8, 9, 10]
    ]
)

print(arr[0:2, 2])

[3 8]


In [56]:
arr = np.array(
    [
        [1, 2, 3, 4, 5], 
        [6, 7, 8, 9, 10],
        [11, 12, 13, 14, 15]
    ]
)

print(arr[1:3, 0:2])

[[ 6  7]
 [11 12]]
