In [1]:
import numpy as np

In [2]:
np.__version__

'2.5.3'

In [4]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

#### To create an nd array we can pass a list, tuple or any array-like object into the array() methods, and it will be converted into an nd array.

In [7]:
arr = np.array((1, 2, 3, 4))
type(arr)

numpy.ndarray

In [10]:
arr = np.array({1, 2, 3, 4, 1})
arr, type(arr)

(array({1, 2, 3, 4}, dtype=object), numpy.ndarray)

#### 0-D array or Scalars

In [11]:
arr = np.array(50)
arr

array(50)

#### 1-D array or uni-dimensional array or vector

In [12]:
arr = np.array(

    [1, 2, 3, 4, 5, 6]

)
arr

array([1, 2, 3, 4, 5, 6])

#### 2-D Array or Matrix or 2nd order tensors

In [13]:
arr = np.array(
    [
        [1, 2, 3], [4, 5, 6]
    ]
)
arr

array([[1, 2, 3],
       [4, 5, 6]])

#### 3-D Array or 3rd order tensor

In [16]:
arr = np.array(
    [
        [
            [1, 2, 3], [4, 5, 6]
        ], 
        [
            [11, 22, 33], [44, 55, 66]
        ]
    ]
)
arr.ndim

3

#### 4-D Array or 4th order tensor

In [21]:
arr = np.array(
    [
        [
            [
                [1, 2, 3], [4, 5, 6]
            ]
        ]
    ]
)
arr.ndim

4

#### ndim is a method to check the dimensions

In [22]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Array Size

In [27]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.size)
print(b.size)
print(c.size)
print(d.size)

1
5
6
12


Array Shape

In [28]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

()
(5,)
(2, 3)
(2, 2, 3)


#### Higher Dimensional Array
When the array is created, you can define the number of dimensions by using the ndmin argument.

In [24]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5
